# Generated by Django 3.2.4 on 2021-06-04 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('number_of_check', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.UUIDField(default=uuid.UUID('92a86546-e6b2-4ce0-bd94-10cbb0a3ca2b'), primary_key=True, serialize=False)),
                ('dsp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ping', models.TimeField()),
                ('bytes_sent', models.CharField(max_length=300)),
                ('bytes_recieve', models.CharField(max_length=300)),
                ('servid', models.SmallIntegerField()),
                ('testdata', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speed.customers')),
            ],
            options={
                'ordering': ['-testdata'],
            },
        ),
    ]
